/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'slemay' at '4/29/17 11:24 AM' with Gradle 2.14.1
 *
 * @author slemay, @date 4/29/17 11:24 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
